import Head from "next/head"

import { AppShell } from "@mantine/core"
import { FooterItem } from "../Footer/Footer"
import { HeaderItem } from "../Header/Header"
import { footerData } from "./data"

type Props = {
  children: React.ReactNode
}

export function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Mission to Mars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        header={<HeaderItem wrapperCondition />}
        footer={<FooterItem {...footerData} />}
        styles={{
          main: {
            backgroundColor: "whitesmoke",
            minHeight: "100vh",
            paddingLeft: "0",
            paddingRight: "0",
            paddingTop: "0"
          }
        }}
      >
        {children}
      </AppShell>
    </>
  )
}
