import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "@/styles/Home.module.css"
import { ActionIcon, AppShell, Button, Container, Grid, Header, Navbar, SimpleGrid } from "@mantine/core"
import { Icon24Hours } from "@tabler/icons-react"
import HomeItem from "@/components/HomeItem"
import Layout from "@/components/Layout"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid>
          <Grid.Col md={6} p={6}>
            Hello
            <HomeItem />
          </Grid.Col>
          <Grid.Col md={6} p={6}>
            Hello
          </Grid.Col>
          <Grid.Col md={6} p={6}>
            Hello
          </Grid.Col>
          <Grid.Col md={6} p={6}>
            Hello
          </Grid.Col>
        </Grid>
        <SimpleGrid cols={2} spacing="md">
          <div>Goodbye</div>
          <div>Goodbye</div>
          <div>Goodbye</div>
          <div>Goodbye</div>
          <div>
            Goodbye
            <Icon24Hours />
            {/* <Button leftIcon={<IconNoCopyright />}>Click me</Button> */}
          </div>
          <ActionIcon color="black" variant="filled"></ActionIcon>
        </SimpleGrid>
      </Layout>
    </>
  )
}
