import Head from "next/head"

import { AppShell } from "@mantine/core"
import { HeaderItem } from "./Header/Header"
import { SideNav } from "./SideNav"

type Props = {
  children: React.ReactNode
}

export function LayoutDashboard({ children }: Props) {
  return (
    <>
      <Head>
        <title>Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        fixed={false}
        header={<HeaderItem />}
        navbar={<SideNav />}
        padding="md"
        styles={(theme) => ({
          body: { minHeight: "100vh" },
          main: { padding: 0, backgroundColor: theme.colors.gray[0] }
        })}
      >
        {children}
      </AppShell>
    </>
  )
}
