import { AppShell } from "@mantine/core"
import Head from "next/head"
import FooterItem from "./Footer"
import HeaderItem from "./Header"
import NavBarItem from "./NavBar"

type Props = {
  children: React.ReactNode
}

export function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        header={<HeaderItem />}
        navbar={<NavBarItem />}
        footer={<FooterItem />}
        styles={{
          main: {
            backgroundColor: "whitesmoke",
            minHeight: "100vh",
            minWidth: "100vw"
          }
        }}
      >
        {children}
      </AppShell>
    </>
  )
}
