import Head from "next/head"
import { AppShell } from "@mantine/core"
import { FooterItem } from "./Footer/Footer"
import { HeaderItem } from "./Header/Header"

type Props = {
  children: React.ReactNode
}

const footerData = {
  data: [
    {
      title: "About",
      links: [
        {
          label: "Features",
          link: "#"
        },
        {
          label: "Pricing",
          link: "#"
        },
        {
          label: "Support",
          link: "#"
        },
        {
          label: "Forums",
          link: "#"
        }
      ]
    },
    {
      title: "Project",
      links: [
        {
          label: "Contribute",
          link: "#"
        },
        {
          label: "Media assets",
          link: "#"
        },
        {
          label: "Changelog",
          link: "#"
        },
        {
          label: "Releases",
          link: "#"
        }
      ]
    },
    {
      title: "Community",
      links: [
        {
          label: "Join Discord",
          link: "#"
        },
        {
          label: "Follow on Twitter",
          link: "#"
        },
        {
          label: "Email newsletter",
          link: "#"
        },
        {
          label: "GitHub discussions",
          link: "#"
        }
      ]
    }
  ]
}

export function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        header={<HeaderItem wrapperCondition />}
        footer={<FooterItem {...footerData} />}
        styles={{
          main: {
            backgroundColor: "whitesmoke",
            minHeight: "100vh",
            paddingLeft: "0",
            paddingRight: "0",
            paddingTop: "0"
          }
        }}
      >
        {children}
      </AppShell>
    </>
  )
}
